;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-append
        evil-backward-char
        evil-delete-backward-char-and-join
        evil-forward-char
        evil-insert
        evil-next-line
        evil-normal-state
        evil-previous-line
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        ))
