;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-delete
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-ex
        evil-forward-char
        evil-insert
        evil-normal-state
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        evil-mouse-drag-region
        ))
